name: linting, testing, building
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Starting Node.js 16
        uses: actions/setup-node@v5
        with:
          node-version: 16
          cache: npm
      - name: install modules
        id: install
        run: npm ci
      - name: build production project
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint:ts
        if: ${{ !cancelled() && steps.install.outcome == 'success' }}
      - name: linting css
        run: npm run lint:scss
        if: ${{ !cancelled() && steps.install.outcome == 'success' }}
      - name: unit testing
        run: npm run test:unit
        if: ${{ !cancelled() && steps.install.outcome == 'success' }}
      - name: build storybook
        run: npm run storybook:build
        if: ${{ !cancelled() && steps.install.outcome == 'success' }}
